// Generated by CoffeeScript 1.8.0
(function() {
  // Compiled from src/dragon.coffee
  var Dragon, SleepingKingStudios;

  SleepingKingStudios = require('./sleeping_king_studios').SleepingKingStudios;

  Dragon = {
    greet: SleepingKingStudios.Greeter.greet,
    roar: function() {
      return 'Roar!';
    }
  };

  // Compiled from src/dragon/card.coffee
  Dragon.Card = (function() {
    function Card() {}

    return Card;

  })();

  // Compiled from src/dragon/deck.coffee
  Dragon.Deck = (function() {
    function Deck() {}

    return Deck;

  })();

  // Compiled from src/dragon/game.coffee
  Dragon.Game = (function() {
    function Game() {}

    return Game;

  })();

  // Compiled from src/dragon/player.coffee
  Dragon.Player = (function() {
    function Player() {}

    return Player;

  })();

  if (typeof exports !== 'undefined') {
    if (typeof module !== 'undefined' && module.exports) {
      exports = module.exports = Dragon;
    }
    exports.CardDragon = Dragon;
  } else {
    this.CardDragon = Dragon;
  }
}).call(this);
