// Generated by CoffeeScript 1.8.0
(function() {
  var SleepingKingStudios, exports;

  SleepingKingStudios = {};

  SleepingKingStudios.Greeter = {
    greet: function() {
      return 'Greetings, starfighter!';
    }
  };

  if (typeof exports !== 'undefined') {
    if (typeof module !== 'undefined' && module.exports) {
      exports = module.exports = SleepingKingStudios;
    }
    exports.SleepingKingStudios = SleepingKingStudios;
  } else {
    this.SleepingKingStudios = SleepingKingStudios;
  }

}).call(this);
